- name: Install Stable repos
  community.kubernetes.helm_repository:
    name: cetic
    repo_url: "https://cetic.github.io/helm-charts"

- name: Create namespace
  community.kubernetes.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: namespace
    state: present

- name: Add Voight.org Certificates
  kubernetes.core.helm:
    name: "{{ namespace }}-certificates"
    chart_ref: ./roles/phpLDAPadmin/files/certificates
    release_namespace: "{{ namespace }}"
    release_values:
      namespace: "{{ namespace }}"
      tls:
        key: "{{ voightorgkey }}"
        crt: "{{ voightorgcrt }}"
        ca: "{{ voightorgca }}"

- name: Apply phpLDAPAdmin
  kubernetes.core.helm:
    name: "{{ deployment }}"
    chart_ref: cetic/phpldapadmin
    release_namespace: "{{ namespace }}"
    release_values:
      env:
        PHPLDAPADMIN_LDAP_HOSTS: "openldap.{{ namespace }}.svc.cluster.local"
        PHPLDAPADMIN_HTTPS: "false"
        PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
      image:
        tag: 0.9.0
      service:
        loadBalancerIP: 192.168.137.78
        type: LoadBalancer
      ingress:
        enabled: true
        hosts:
          - phpldapadmin.voight.org
        tls:
        - secretName: "site-cert"
          hosts:
          - phpldapadmin.voight.org
      readinessProbe:
        httpGet:
          path: /
          port: http
        periodSeconds: 30
      livenessProbe:
        httpGet:
          path: /
          port: http
        periodSeconds: 30

