- name: Initialize Kubernetes Control Plane
  hosts: controlplane
  var:
    namespace: authentication

  tasks:
    - name: Install cetic repos
      community.kubernetes.helm_repository:
        name: cetic
        repo_url: "https://haproxytech.github.io/helm-charts"

    - name: Update cetic repos
      command: helm repo update

    - name: Apply phpldapadmin chart
      command: helm install -n {{ namespace }} phpldapadmin cetic/phpldapadmin -f ~/privateKube/phpldapadmin.yaml
