- name: Initialize Kubernetes Control Plane
  hosts: controlplane
  vars:
    namespace: authentication

  tasks:
    - name: Install cetic repos
      community.kubernetes.helm_repository:
        name: cetic
        repo_url: "https://cetic.github.io/helm-charts"
      delegate_to: localhost

    - name: Update cetic repos
      command: helm repo update
      delegate_to: localhost

    - name: Apply phpldapadmin chart
      command: helm upgrade -i -n {{ namespace }} phpldapadmin cetic/phpldapadmin -f ../phpldapadmin.yaml
      delegate_to: localhost
