apiVersion: v1
kind: Secret
metadata:
  name: openldap-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  LDAP_CONFIG_PASSWORD: {{ .Values.openldapconfig.password | b64enc }}
  LDAP_ADMIN_PASSWORD: {{ .Values.openldapadmin.password | b64enc }}